// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *About → Service*
 */
export interface AboutDocumentDataServiceItem {
  /**
   * Title field in *About → Service*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.service[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *About → Service*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.service[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Image field in *About → Service*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.service[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

type AboutDocumentDataSlicesSlice = never;

/**
 * Content for About documents
 */
interface AboutDocumentData {
  /**
   * Biography field in *About*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.biography
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  biography: prismic.RichTextField;

  /**
   * Website Url field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.website_url
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  website_url: prismic.KeyTextField;

  /**
   * Email field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.email
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;

  /**
   * Phone field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.phone
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phone: prismic.KeyTextField;

  /**
   * Address field in *About*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.address
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  address: prismic.RichTextField;

  /**
   * Linked In field in *About*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: about.linked_in
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linked_in: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Instagram field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.instagram
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  instagram: prismic.KeyTextField;

  /**
   * Twitter field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.twitter
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  twitter: prismic.KeyTextField;

  /**
   * Service field in *About*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about.service[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  service: prismic.GroupField<Simplify<AboutDocumentDataServiceItem>>;

  /**
   * Slice Zone field in *About*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AboutDocumentDataSlicesSlice> /**
   * Meta Title field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: about.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: about.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *About*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * About document from Prismic
 *
 * - **API ID**: `about`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<AboutDocumentData>, "about", Lang>;

/**
 * Item in *Homepage → Homepage Projects Group*
 */
export interface HomepageDocumentDataHomepageProjectsGroupItem {
  /**
   * Project field in *Homepage → Homepage Projects Group*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.homepage_projects_group[].project
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  project: prismic.ContentRelationshipField<"project">;
}

type HomepageDocumentDataSlicesSlice = HomepageProjectsSelectSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Homepage Projects Group field in *Homepage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.homepage_projects_group[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  homepage_projects_group: prismic.GroupField<
    Simplify<HomepageDocumentDataHomepageProjectsGroupItem>
  >;

  /**
   * Introduction field in *Homepage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.introduction
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  introduction: prismic.RichTextField;

  /**
   * Email field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.email
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;

  /**
   * Phone Number field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.phone_number
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phone_number: prismic.KeyTextField;

  /**
   * Website Url field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.website_url
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  website_url: prismic.KeyTextField;

  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

type IndexDocumentDataSlicesSlice = IndexProjectsSelectSlice;

/**
 * Content for Index documents
 */
interface IndexDocumentData {
  /**
   * Slice Zone field in *Index*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: index.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<IndexDocumentDataSlicesSlice> /**
   * Meta Title field in *Index*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: index.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Index*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: index.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Index*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: index.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Index document from Prismic
 *
 * - **API ID**: `index`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type IndexDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<IndexDocumentData>, "index", Lang>;

/**
 * Item in *News → News Item*
 */
export interface NewsDocumentDataNewsItemItem {
  /**
   * Date field in *News → News Item*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: news.news_item[].date
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  date: prismic.KeyTextField;

  /**
   * Title field in *News → News Item*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: news.news_item[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Image field in *News → News Item*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: news.news_item[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Body Text field in *News → News Item*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: news.news_item[].body_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body_text: prismic.RichTextField;
}

type NewsDocumentDataSlicesSlice = never;

/**
 * Content for News documents
 */
interface NewsDocumentData {
  /**
   * News Item field in *News*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: news.news_item[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  news_item: prismic.GroupField<Simplify<NewsDocumentDataNewsItemItem>>;

  /**
   * Slice Zone field in *News*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: news.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<NewsDocumentDataSlicesSlice> /**
   * Meta Title field in *News*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: news.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *News*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: news.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *News*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: news.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * News document from Prismic
 *
 * - **API ID**: `news`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NewsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<NewsDocumentData>, "news", Lang>;

type PageDocumentDataSlicesSlice = never;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

type ProjectDocumentDataSlices1Slice = ImageSlice;

type ProjectDocumentDataSlices3Slice = RichTextSlice | ProjectPageImageSlice;

/**
 * Content for Project documents
 */
interface ProjectDocumentData {
  /**
   * Title field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * SubTitle field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Eg. Design Management for Office Group
   * - **API ID Path**: project.subtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Design Architects field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.design_architects
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  design_architects: prismic.KeyTextField;

  /**
   * Technical Architects field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.technical_architects
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  technical_architects: prismic.KeyTextField;

  /**
   * Net Internal Area field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.net_internal_area
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  net_internal_area: prismic.KeyTextField;

  /**
   * Completion Date field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.completion_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  completion_date: prismic.KeyTextField;

  /**
   * Client field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.client
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  client: prismic.KeyTextField;

  /**
   * Service field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.service
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  service: prismic.KeyTextField;

  /**
   * Location field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.location
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  location: prismic.KeyTextField;

  /**
   * Description field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Related Project 1 field in *Project*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: project.related_project_1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  related_project_1: prismic.ContentRelationshipField<"project">;

  /**
   * Related Project 2 field in *Project*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: project.related_project_2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  related_project_2: prismic.ContentRelationshipField;

  /**
   * Related Project Image field in *Project*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.related_project_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  related_project_image: prismic.ImageField<never> /**
   * Slice Zone field in *Project*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: project.slices1[]
   * - **Tab**: Homepage Content
   * - **Documentation**: https://prismic.io/docs/field#slices
   */;
  slices1: prismic.SliceZone<ProjectDocumentDataSlices1Slice> /**
   * Meta Title field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.meta_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.meta_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField /**
   * Hero Image field in *Project*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.hero_image
   * - **Tab**: Project Page Content
   * - **Documentation**: https://prismic.io/docs/field#image
   */;
  hero_image: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Project*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: project.slices3[]
   * - **Tab**: Project Page Content
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices3: prismic.SliceZone<ProjectDocumentDataSlices3Slice>;
}

/**
 * Project document from Prismic
 *
 * - **API ID**: `project`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProjectDocumentData>,
    "project",
    Lang
  >;

export type AllDocumentTypes =
  | AboutDocument
  | HomepageDocument
  | IndexDocument
  | NewsDocument
  | PageDocument
  | ProjectDocument;

/**
 * Item in *HomepageProjectsSelect → Default → Primary → ProjectsGroup*
 */
export interface HomepageProjectsSelectSliceDefaultPrimaryProjectsgroupItem {
  /**
   * Project field in *HomepageProjectsSelect → Default → Primary → ProjectsGroup*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage_projects_select.default.primary.projectsgroup[].project
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  project: prismic.ContentRelationshipField<"project">;
}

/**
 * Primary content in *HomepageProjectsSelect → Default → Primary*
 */
export interface HomepageProjectsSelectSliceDefaultPrimary {
  /**
   * ProjectsGroup field in *HomepageProjectsSelect → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage_projects_select.default.primary.projectsgroup[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  projectsgroup: prismic.GroupField<
    Simplify<HomepageProjectsSelectSliceDefaultPrimaryProjectsgroupItem>
  >;
}

/**
 * Default variation for HomepageProjectsSelect Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomepageProjectsSelectSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HomepageProjectsSelectSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HomepageProjectsSelect*
 */
type HomepageProjectsSelectSliceVariation = HomepageProjectsSelectSliceDefault;

/**
 * HomepageProjectsSelect Shared Slice
 *
 * - **API ID**: `homepage_projects_select`
 * - **Description**: HomepageProjectsSelect
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomepageProjectsSelectSlice = prismic.SharedSlice<
  "homepage_projects_select",
  HomepageProjectsSelectSliceVariation
>;

/**
 * Primary content in *Image → 1x Landscape Image → Primary*
 */
export interface ImageSlice1XLandscapeImagePrimary {
  /**
   * Position field in *Image → 1x Landscape Image → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Left
   * - **API ID Path**: image.1XLandscapeImage.primary.position
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  position: prismic.SelectField<"Left" | "Right", "filled">;

  /**
   * Image field in *Image → 1x Landscape Image → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.1XLandscapeImage.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * 1x Landscape Image variation for Image Slice
 *
 * - **API ID**: `1XLandscapeImage`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSlice1XLandscapeImage = prismic.SharedSliceVariation<
  "1XLandscapeImage",
  Simplify<ImageSlice1XLandscapeImagePrimary>,
  never
>;

/**
 * Primary content in *Image → 2x Landscape Image → Primary*
 */
export interface ImageSlice2XLandscapeImagePrimary {
  /**
   * Position field in *Image → 2x Landscape Image → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Left
   * - **API ID Path**: image.2XLandscapeImage.primary.position
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  position: prismic.SelectField<"Left" | "Right", "filled">;

  /**
   * Image 1 field in *Image → 2x Landscape Image → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.2XLandscapeImage.primary.image_1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_1: prismic.ImageField<never>;

  /**
   * Image 2 field in *Image → 2x Landscape Image → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.2XLandscapeImage.primary.image_2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_2: prismic.ImageField<never>;
}

/**
 * 2x Landscape Image variation for Image Slice
 *
 * - **API ID**: `2XLandscapeImage`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSlice2XLandscapeImage = prismic.SharedSliceVariation<
  "2XLandscapeImage",
  Simplify<ImageSlice2XLandscapeImagePrimary>,
  never
>;

/**
 * Primary content in *Image → 1x Portrait Image → Primary*
 */
export interface ImageSlice1XPortraitImagePrimary {
  /**
   * Position field in *Image → 1x Portrait Image → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Top
   * - **API ID Path**: image.1XPortraitImage.primary.position
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  position: prismic.SelectField<"Top" | "Bottom", "filled">;

  /**
   * Image field in *Image → 1x Portrait Image → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.1XPortraitImage.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * 1x Portrait Image variation for Image Slice
 *
 * - **API ID**: `1XPortraitImage`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSlice1XPortraitImage = prismic.SharedSliceVariation<
  "1XPortraitImage",
  Simplify<ImageSlice1XPortraitImagePrimary>,
  never
>;

/**
 * Primary content in *Image → 2x Portrait Image → Primary*
 */
export interface ImageSlice2XPortraitImagePrimary {
  /**
   * Position field in *Image → 2x Portrait Image → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Top
   * - **API ID Path**: image.2XPortraitImage.primary.position
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  position: prismic.SelectField<"Top" | "Bottom", "filled">;

  /**
   * Image 1 field in *Image → 2x Portrait Image → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.2XPortraitImage.primary.image_1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_1: prismic.ImageField<never>;

  /**
   * Image 2 field in *Image → 2x Portrait Image → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.2XPortraitImage.primary.image_2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_2: prismic.ImageField<never>;
}

/**
 * 2x Portrait Image variation for Image Slice
 *
 * - **API ID**: `2XPortraitImage`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSlice2XPortraitImage = prismic.SharedSliceVariation<
  "2XPortraitImage",
  Simplify<ImageSlice2XPortraitImagePrimary>,
  never
>;

/**
 * Primary content in *Image → Full Bleed Image → Primary*
 */
export interface ImageSliceFullBleedImagePrimary {
  /**
   * Image field in *Image → Full Bleed Image → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.fullBleedImage.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Full Bleed Image variation for Image Slice
 *
 * - **API ID**: `fullBleedImage`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliceFullBleedImage = prismic.SharedSliceVariation<
  "fullBleedImage",
  Simplify<ImageSliceFullBleedImagePrimary>,
  never
>;

/**
 * Slice variation for *Image*
 */
type ImageSliceVariation =
  | ImageSlice1XLandscapeImage
  | ImageSlice2XLandscapeImage
  | ImageSlice1XPortraitImage
  | ImageSlice2XPortraitImage
  | ImageSliceFullBleedImage;

/**
 * Image Shared Slice
 *
 * - **API ID**: `image`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSlice = prismic.SharedSlice<"image", ImageSliceVariation>;

/**
 * Item in *IndexProjectsSelect → Default → Primary → Projects Group*
 */
export interface IndexProjectsSelectSliceDefaultPrimaryProjectsGroupItem {
  /**
   * Project field in *IndexProjectsSelect → Default → Primary → Projects Group*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: index_projects_select.default.primary.projects_group[].project
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  project: prismic.ContentRelationshipField<"project">;
}

/**
 * Primary content in *IndexProjectsSelect → Default → Primary*
 */
export interface IndexProjectsSelectSliceDefaultPrimary {
  /**
   * Projects Group field in *IndexProjectsSelect → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: index_projects_select.default.primary.projects_group[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  projects_group: prismic.GroupField<
    Simplify<IndexProjectsSelectSliceDefaultPrimaryProjectsGroupItem>
  >;
}

/**
 * Default variation for IndexProjectsSelect Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IndexProjectsSelectSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<IndexProjectsSelectSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *IndexProjectsSelect*
 */
type IndexProjectsSelectSliceVariation = IndexProjectsSelectSliceDefault;

/**
 * IndexProjectsSelect Shared Slice
 *
 * - **API ID**: `index_projects_select`
 * - **Description**: IndexProjectsSelect
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IndexProjectsSelectSlice = prismic.SharedSlice<
  "index_projects_select",
  IndexProjectsSelectSliceVariation
>;

/**
 * Primary content in *ProjectPageImage → 1x Landscape Image → Primary*
 */
export interface ProjectPageImageSlice1XLandscapeImagePrimary {
  /**
   * Position field in *ProjectPageImage → 1x Landscape Image → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Left
   * - **API ID Path**: project_page_image.1XLandscapeImage.primary.position
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  position: prismic.SelectField<"Left" | "Right", "filled">;

  /**
   * Image field in *ProjectPageImage → 1x Landscape Image → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_page_image.1XLandscapeImage.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Caption field in *ProjectPageImage → 1x Landscape Image → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_page_image.1XLandscapeImage.primary.caption
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  caption: prismic.KeyTextField;
}

/**
 * 1x Landscape Image variation for ProjectPageImage Slice
 *
 * - **API ID**: `1XLandscapeImage`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectPageImageSlice1XLandscapeImage =
  prismic.SharedSliceVariation<
    "1XLandscapeImage",
    Simplify<ProjectPageImageSlice1XLandscapeImagePrimary>,
    never
  >;

/**
 * Primary content in *ProjectPageImage → 2x Landscape Image → Primary*
 */
export interface ProjectPageImageSlice2XLandscapeImagePrimary {
  /**
   * Position field in *ProjectPageImage → 2x Landscape Image → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Left
   * - **API ID Path**: project_page_image.2XLandscapeImage.primary.position
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  position: prismic.SelectField<"Left" | "Right", "filled">;

  /**
   * Image 1 field in *ProjectPageImage → 2x Landscape Image → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_page_image.2XLandscapeImage.primary.image_1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_1: prismic.ImageField<never>;

  /**
   * Caption 1 field in *ProjectPageImage → 2x Landscape Image → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_page_image.2XLandscapeImage.primary.caption_1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  caption_1: prismic.KeyTextField;

  /**
   * Image 2 field in *ProjectPageImage → 2x Landscape Image → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_page_image.2XLandscapeImage.primary.image_2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_2: prismic.ImageField<never>;

  /**
   * Caption 2 field in *ProjectPageImage → 2x Landscape Image → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_page_image.2XLandscapeImage.primary.caption_2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  caption_2: prismic.KeyTextField;
}

/**
 * 2x Landscape Image variation for ProjectPageImage Slice
 *
 * - **API ID**: `2XLandscapeImage`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectPageImageSlice2XLandscapeImage =
  prismic.SharedSliceVariation<
    "2XLandscapeImage",
    Simplify<ProjectPageImageSlice2XLandscapeImagePrimary>,
    never
  >;

/**
 * Primary content in *ProjectPageImage → 1x Portrait Image → Primary*
 */
export interface ProjectPageImageSlice1XPortraitImagePrimary {
  /**
   * Position field in *ProjectPageImage → 1x Portrait Image → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Left
   * - **API ID Path**: project_page_image.1XPortraitImage.primary.position
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  position: prismic.SelectField<"Left" | "Right", "filled">;

  /**
   * Image field in *ProjectPageImage → 1x Portrait Image → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_page_image.1XPortraitImage.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Caption field in *ProjectPageImage → 1x Portrait Image → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_page_image.1XPortraitImage.primary.caption
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  caption: prismic.KeyTextField;
}

/**
 * 1x Portrait Image variation for ProjectPageImage Slice
 *
 * - **API ID**: `1XPortraitImage`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectPageImageSlice1XPortraitImage = prismic.SharedSliceVariation<
  "1XPortraitImage",
  Simplify<ProjectPageImageSlice1XPortraitImagePrimary>,
  never
>;

/**
 * Primary content in *ProjectPageImage → 2x Portrait Image → Primary*
 */
export interface ProjectPageImageSlice2XPortraitImagePrimary {
  /**
   * Position field in *ProjectPageImage → 2x Portrait Image → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Left
   * - **API ID Path**: project_page_image.2XPortraitImage.primary.position
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  position: prismic.SelectField<"Left" | "Right", "filled">;

  /**
   * Image 1 field in *ProjectPageImage → 2x Portrait Image → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_page_image.2XPortraitImage.primary.image_1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_1: prismic.ImageField<never>;

  /**
   * Caption 1 field in *ProjectPageImage → 2x Portrait Image → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_page_image.2XPortraitImage.primary.caption_1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  caption_1: prismic.KeyTextField;

  /**
   * Image 2 field in *ProjectPageImage → 2x Portrait Image → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_page_image.2XPortraitImage.primary.image_2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_2: prismic.ImageField<never>;

  /**
   * Caption 2 field in *ProjectPageImage → 2x Portrait Image → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_page_image.2XPortraitImage.primary.caption_2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  caption_2: prismic.KeyTextField;
}

/**
 * 2x Portrait Image variation for ProjectPageImage Slice
 *
 * - **API ID**: `2XPortraitImage`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectPageImageSlice2XPortraitImage = prismic.SharedSliceVariation<
  "2XPortraitImage",
  Simplify<ProjectPageImageSlice2XPortraitImagePrimary>,
  never
>;

/**
 * Primary content in *ProjectPageImage → Full Bleed Image → Primary*
 */
export interface ProjectPageImageSliceFullBleedImagePrimary {
  /**
   * Image field in *ProjectPageImage → Full Bleed Image → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_page_image.fullBleedImage.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Caption field in *ProjectPageImage → Full Bleed Image → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_page_image.fullBleedImage.primary.caption
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  caption: prismic.KeyTextField;
}

/**
 * Full Bleed Image variation for ProjectPageImage Slice
 *
 * - **API ID**: `fullBleedImage`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectPageImageSliceFullBleedImage = prismic.SharedSliceVariation<
  "fullBleedImage",
  Simplify<ProjectPageImageSliceFullBleedImagePrimary>,
  never
>;

/**
 * Slice variation for *ProjectPageImage*
 */
type ProjectPageImageSliceVariation =
  | ProjectPageImageSlice1XLandscapeImage
  | ProjectPageImageSlice2XLandscapeImage
  | ProjectPageImageSlice1XPortraitImage
  | ProjectPageImageSlice2XPortraitImage
  | ProjectPageImageSliceFullBleedImage;

/**
 * ProjectPageImage Shared Slice
 *
 * - **API ID**: `project_page_image`
 * - **Description**: ProjectPageImage
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectPageImageSlice = prismic.SharedSlice<
  "project_page_image",
  ProjectPageImageSliceVariation
>;

/**
 * Primary content in *RichText → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Text field in *RichText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum...
   * - **API ID Path**: rich_text.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutDocument,
      AboutDocumentData,
      AboutDocumentDataServiceItem,
      AboutDocumentDataSlicesSlice,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataHomepageProjectsGroupItem,
      HomepageDocumentDataSlicesSlice,
      IndexDocument,
      IndexDocumentData,
      IndexDocumentDataSlicesSlice,
      NewsDocument,
      NewsDocumentData,
      NewsDocumentDataNewsItemItem,
      NewsDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      ProjectDocument,
      ProjectDocumentData,
      ProjectDocumentDataSlices1Slice,
      ProjectDocumentDataSlices3Slice,
      AllDocumentTypes,
      HomepageProjectsSelectSlice,
      HomepageProjectsSelectSliceDefaultPrimaryProjectsgroupItem,
      HomepageProjectsSelectSliceDefaultPrimary,
      HomepageProjectsSelectSliceVariation,
      HomepageProjectsSelectSliceDefault,
      ImageSlice,
      ImageSlice1XLandscapeImagePrimary,
      ImageSlice2XLandscapeImagePrimary,
      ImageSlice1XPortraitImagePrimary,
      ImageSlice2XPortraitImagePrimary,
      ImageSliceFullBleedImagePrimary,
      ImageSliceVariation,
      ImageSlice1XLandscapeImage,
      ImageSlice2XLandscapeImage,
      ImageSlice1XPortraitImage,
      ImageSlice2XPortraitImage,
      ImageSliceFullBleedImage,
      IndexProjectsSelectSlice,
      IndexProjectsSelectSliceDefaultPrimaryProjectsGroupItem,
      IndexProjectsSelectSliceDefaultPrimary,
      IndexProjectsSelectSliceVariation,
      IndexProjectsSelectSliceDefault,
      ProjectPageImageSlice,
      ProjectPageImageSlice1XLandscapeImagePrimary,
      ProjectPageImageSlice2XLandscapeImagePrimary,
      ProjectPageImageSlice1XPortraitImagePrimary,
      ProjectPageImageSlice2XPortraitImagePrimary,
      ProjectPageImageSliceFullBleedImagePrimary,
      ProjectPageImageSliceVariation,
      ProjectPageImageSlice1XLandscapeImage,
      ProjectPageImageSlice2XLandscapeImage,
      ProjectPageImageSlice1XPortraitImage,
      ProjectPageImageSlice2XPortraitImage,
      ProjectPageImageSliceFullBleedImage,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
    };
  }
}
