// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  homepage_landscape_image_x1: dynamic(
    () => import("./HomepageLandscapeImageX1"),
  ),
  homepage_landscape_image_x2: dynamic(
    () => import("./HomepageLandscapeImageX2"),
  ),
  homepage_projects_select: dynamic(() => import("./HomepageProjectsSelect")),
  image: dynamic(() => import("./Image")),
  rich_text: dynamic(() => import("./RichText")),
};
